services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    # --- Command
    moustache.command.clean_downloads:
        class: "MoustacheBundle\\Command\\CleanDownloadsCommand"
        arguments:
            - "@moustache.task.clean_downloads"
        tags:
            - { name: console.command }
    moustache.command.generate_signup:
        class: "MoustacheBundle\\Command\\GenerateSignupCommand"
        arguments:
            - "@torrent.repository.user"
            - "@torrent.manager.user"
            - "@router"
        tags:
            - { name: console.command }
    moustache.command.install:
        class: "MoustacheBundle\\Command\\InstallCommand"
        arguments:
            - "@moustache.task.symlink_parameters"
        tags:
            - { name: console.command }

    # --- Controllers
    moustache.controller.add:
        class: "MoustacheBundle\\Controller\\AddController"
        arguments:
            - "@moustache.form.torrent_menu"
            - "@torrent.client.current"
            - "@torrent.manager.torrent"
            - "@moustache.service.redirector"
            - "@request_stack"
            - "@monolog.logger.moustache"
            - "%torrent_rpc_client%"
        public: true
    moustache.controller.default:
        class: "MoustacheBundle\\Controller\\DefaultController"
        arguments:
            - "@torrent.client.current"
            - "@templating"
            - "@moustache.form.torrent_menu"
        public: true
    moustache.controller.download:
        class: "MoustacheBundle\\Controller\\DownloadController"
        arguments:
            - "@torrent.client.current"
            - "@moustache.service.torrent_publisher"
            - "@moustache.service.redirector"
        public: true
    moustache.controller.life_cycle:
        class: "MoustacheBundle\\Controller\\LifeCycleController"
        arguments:
            - "@torrent.client.current"
            - "@moustache.service.redirector"
        public: true
    moustache.controller.remove:
        class: "MoustacheBundle\\Controller\\RemoveController"
        arguments:
            - "@torrent.client.current"
            - "@moustache.service.redirector"
        public: true
    moustache.controller.signup:
        class: "MoustacheBundle\\Controller\\SignupController"
        arguments:
            - "@templating"
            - "@torrent.manager.user"
            - "@torrent.repository.user"
            - "@moustache.form.signup"
            - "@fos_user.security.login_manager"
            - "@moustache.service.redirector"
            - "@request_stack"
        public: true
    moustache.controller.status:
        class: "MoustacheBundle\\Controller\\StatusController"
        arguments:
            - "@torrent.client.current"
        public: true


    # --- Event Listeners
    moustache.event_listener.cache_outdated_redirector:
        class: "MoustacheBundle\\EventListener\\CacheOutdatedRedirectorListener"
        arguments:
            - "@moustache.service.redirector"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -50 }
    MoustacheBundle\EventListener\UserGreeterListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1 }
    moustache.event_listener.maintenance:
        class: "MoustacheBundle\\EventListener\\MaintenanceListener"
        arguments:
            - "%maintenance_lock_file%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 2000}
    MoustacheBundle\EventListener\MissingTorrentWarnerListener:
        tags:
            - { name: kernel.event_listener, event: torrent.missing, method: onTorrentMissing, priority: 0}
    moustache.event_listener.locale_setter:
        class: "MoustacheBundle\\EventListener\\LocaleSetterListener"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200}

    # --- Message
    MoustacheBundle\Message\:
        resource: '../../../MoustacheBundle/Message/*'
    MoustacheBundle\Message\Handler\:
        resource: '../../../MoustacheBundle/Message/Handler/*'
        tags:
            - { name: message.handler }

    MoustacheBundle\Message\Handler\LogMessageHandler:
        arguments:
            $logger: "@monolog.logger.moustache"
        tags:
            - { name: message.handler }
    moustache.message.flash_handler: '@MoustacheBundle\Message\Handler\FlashMessageHandler'

    # --- Forms
    MoustacheBundle\Form\:
        resource: '../../../MoustacheBundle/Form/*'

    moustache.form.torrent_menu:
        class: Symfony\Component\Form\FormInterface
        factory: 'form.factory:create'
        arguments:
            - "MoustacheBundle\\Form\\TorrentMenu"
            - "@torrent.entity.torrent"
    moustache.form.signup:
        class: Symfony\Component\Form\FormInterface
        factory: 'form.factory:create'
        arguments:
            - "MoustacheBundle\\Form\\Signup"

    # --- Services
    moustache.service.torrent_link_generator:
        class: "MoustacheBundle\\Service\\TorrentLinkGenerator"
        arguments:
            - "@session"
            - "@router"
            - "%kernel.root_dir%"
    moustache.service.torrent_publisher:
        class: "MoustacheBundle\\Service\\TorrentPublisher"
        arguments:
            - "@filesystem"
            - "@moustache.service.torrent_link_generator"
            - "%allow_direct_download%"
    moustache.service.redirector:
        class: "MoustacheBundle\\Service\\Redirector"
        arguments:
            - "@router"
            - "@moustache.message.flash_handler"

    # --- Shortcut
    moustache.shortcut.request:
        class: "Symfony\\Component\\HttpFoundation\\Request"
        factory: 'request_stack:getCurrentRequest'

    # --- Tasks
    moustache.task.clean_downloads:
        class: "MoustacheBundle\\Task\\CleanDownloadsTask"
        arguments:
            - "@moustache.service.torrent_link_generator"
            - "@filesystem"
            - "%clean_downloads_delay_in_seconds%"
    moustache.task.symlink_parameters:
        class: "MoustacheBundle\\Task\\SymlinkParametersTask"
        arguments:
            - "@filesystem"
            - "%kernel.root_dir%"
            - "%system_conf_dir%"

    # --- Twig
    moustache.twig.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
